Draft: Feat/sst theophile
le-phare/le-phare.github.io pull request #118
Opened 2023-10-24 09:28 UTC by pierreboissinot

2023-10-25 16:33 UTC, pierreboissinot reviewed
pour améliorer la DX, nous pourrions ajouter des `echo` indiquant le chemin vers les fichiers écrits.

2023-10-25 16:33 UTC, pierreboissinot commented on tools/trigger_generator_versions_docs.php
> +?>
```suggestion
```

remove redundant closing tag

2023-10-25 16:33 UTC, pierreboissinot commented on versions_data/2023.04.json
> +        "curl",
**suggestion**: trier les valeurs par ordre alphabetique

2023-10-25 16:33 UTC, pierreboissinot commented on versions_data/2023.04.json
> +        "ctype",
**suggestion**: trier les valeurs par ordre alphabetique

2023-10-25 16:33 UTC, pierreboissinot commented on versions_data/2023.04.json
> +        "upload_max_filesize": "32M",
**suggestion**: trier les valeurs par ordre alphabetique

2023-10-25 16:33 UTC, pierreboissinot commented on versions_data/2023.06.json
> +        "mbstring",
**suggestion**: trier les valeurs par ordre alphabetique

2023-10-25 16:33 UTC, pierreboissinot commented on versions_data/2023.06.json
> +        "memcached.sess_lock_wait_min": "150",
**suggestion**: trier les valeurs par ordre alphabetique

2023-10-25 16:33 UTC, pierreboissinot commented on tools/trigger_generator_versions_docs.php
> +        array_push($search, "{{" . $key . "}}");
```suggestion
        $search[] = "{{" . $key . "}}";
```

2023-10-26 07:41 UTC, theophilejeromerocher commented on versions_data/2023.06.json
> +        "memcached.sess_lock_wait_min": "150",
ordre lisible pour l'humain (futur commit avec des "commentaires" dans les settigns)

2023-10-26 08:16 UTC, pierreboissinot commented on versions_data/2023.04.json
> +    "order_in_list": 2,
**question**: est-ce nécessaire ? Un tri desc par ordre alpha ne suffirait-il pas ?

2023-10-27 15:32 UTC, pierreboissinot commented on docs/generated/versions_pages/2023.04.md
> +	opcache.memory_consumption = <=256
**issue**: nous ne devrions pas mettre "<=" ou ">=" dans le md

2023-10-27 15:32 UTC, pierreboissinot commented on docs/generated/versions_pages/2023.06.md
> +Pour être sur que la machine est bien configurée --> tout en vert sur le script PHP, toutes les caches sur ce document cochées.
```suggestion
Pour être sur que la machine est bien configurée --> tout en vert sur le script PHP, toutes les coches sur ce document cochées.
```

2023-11-13 09:07 UTC, thislg requested changes
Il faut appliquer nos règles php cs fixer (yoda style, simples quotes pour les chaînes littérales). Je suis assez dubitatif sur la viabilité de développer un moteur de template custom, le template aurait pu être un script php ou même du twig (cependant je sais qu'on t'a demandé de ne pas utiliser de bibliothèque).

2023-11-13 09:07 UTC, thislg commented on tools/templates/check_version_script_template.php
> +$FAROS_VERSION = $versionData->version; //0.6 // @phpstan-ignore-line
Vérifier la présence de la propriété version. Ça devrait permettre d'enlever phpstan-ignore-line.

2023-12-18 14:49 UTC, pierreboissinot commented on tools/templates/template.md.php
> + * <input type="checkbox"/> <?php echo $versionData->expect_ram_go; ?> Go RAM
```suggestion
 * <input type="checkbox"/> <?php echo $versionData->expected_ram_go; ?> Go RAM
```
refactor pour être cohérent dans le nommage des variables avec la ligne du dessus.

2023-12-18 14:50 UTC, pierreboissinot commented
@theophilejeromerocher pourrais-tu traiter les commentaires non résolus stp ?

2023-12-21 08:36 UTC, pierreboissinot commented
@theophilejeromerocher j'ai résolu les commentaires "outdated", pourrais-tu traiter le reste avec @thislg si besoin pour que la PR soit validée d'ici demain ?

2023-12-22 08:49 UTC, thislg requested changes

2023-12-22 08:49 UTC, thislg commented on tools/readme.md
> +* Créer un nouveau fichier json, la version de faros est stockée dans la clée "version", n'hésitez pas à vous baser sur les json existants.
```suggestion
* Créer un nouveau fichier json, la version de faros est stockée dans la clé "version", n'hésitez pas à vous baser sur les json existants.
```

2023-12-22 08:49 UTC, thislg commented on tools/readme.md
> +* **versions_datas/x.json** --> shared.json stock toutes les informations communes à toutes les versions de faros, chaque fichier *version*.json représente une version individuelle. Voir JSON.
```suggestion
* **versions_datas/x.json** --> shared.json stocke toutes les informations communes à toutes les versions de faros, chaque fichier *version*.json représente une version individuelle. Voir JSON.
```

2023-12-22 08:49 UTC, thislg commented on tools/readme.md
> +	* **Pour les settings** (php.ini), possibilité d'ajouter des opérateurs : <= < > >= pour les valeurs chiffrées attendues. Si l'on souhaite faire un commentaire, une ligne simple à afficher textuelle
Préciser ? On parle d'ajouter un underscore en préfixe ?

```suggestion
	* **Pour les settings** (php.ini), possibilité d'ajouter des opérateurs : <= < > >= pour les valeurs chiffrées attendues. Si l'on souhaite faire un commentaire, une ligne simple à afficher directement sur le markdown, et non testée dans la vérification des settings php, donner une clé préfixée par un underscore du type : "_stringunique".
```

2023-12-22 08:49 UTC, thislg commented on tools/readme.md
> +* Ouvrez le json et modifiez comme vous le souhaitez les informations. Pour ajouter de nouvelles valeurs et les utiliser voir ci-dessus. En fonction de la complexité des changements il est possible q
```suggestion
* Ouvrez le json et modifiez comme vous le souhaitez les informations. Pour ajouter de nouvelles valeurs et les utiliser voir ci-dessus. En fonction de la complexité des changements il est possible qu'il soit nécessaire de toucher aux templates markdown, php voire même le générateur. Une fois des modifications apportées lancer le générateur (voir ci-dessous) pour actualiser la documentation. 
```

2023-12-22 09:09 UTC, thislg commented on tools/readme.md
> +ce dossier et ses sous-dossiers **docs/generated/** --> tous les fichiers générés par le générateur sont situés dans  (documentation Markdown & fichiers de tests scripts php).
Pourquoi "(documentation Markdown & fichiers de tests scripts php)" est entre parenthèses ? La phrase est coupée.

2023-12-22 09:12 UTC, thislg commented on tools/readme.md
> +ce dossier et ses sous-dossiers **docs/generated/** --> tous les fichiers générés par le générateur sont situés dans  (documentation Markdown & fichiers de tests scripts php).
```suggestion
* Le dossier et ses sous-dossiers **docs/generated/** --> contient tous les fichiers générés par le générateur  (documentation Markdown & fichiers de tests scripts php).
```

2023-12-22 09:29 UTC, thislg approved these changes

2023-12-22 10:26 UTC, pierreboissinot commented
on peut merge cet aprem et surveiller que le site est ok ?

2023-12-22 10:28 UTC, thislg commented
@pierreboissinot Vu la semaine de congés qui arrive je pense que ça devrait attendre la première semaine de janvier.

2024-01-03 09:00 UTC, pierreboissinot commented
@thislg vu ensemble, les liens du menu ne foncitonnent pas, Noé s'en charge la semaine prochaine.

2024-01-03 09:45 UTC, merged