feat(requirements): Brotli compression
le-phare/le-phare.github.io pull request #172
Opened 2024-07-01 09:39 UTC by lucasmirloup

Fixes #171

https://www.wrike.com/open.htm?id=1018578189

2024-07-01 09:40 UTC, lucasmirloup commented
La feature est dans le dernier commit : e298b41

2024-07-02 08:18 UTC, thislg requested changes
Il faut mettre à jour le changelog.

2024-07-02 08:18 UTC, thislg commented on .spells
> +php_cs_fixer() {
```suggestion
php-cs-fixer() {
```

Il faut echo le nom exact de la fonction sinon ça ne fonctionne pas. Ici c'est php_cs_fixer qui sera utilisable en CLI.

2024-07-03 12:19 UTC, lucasmirloup commented on .spells
> +php_cs_fixer() {
Bien vu :+1:

2024-07-03 12:20 UTC, lucasmirloup commented
> Il faut mettre à jour le changelog.

Hello, on a un changelog sur ce projet ?
On pourrait crééer une nouvelle version de nos prérequis, mais la configuration Apache est partagée entre toutes les versions...

2024-07-03 12:35 UTC, thislg commented
> > Il faut mettre à jour le changelog.
> 
> Hello, on a un changelog sur ce projet ? On pourrait créer une nouvelle version de nos prérequis, mais la configuration Apache est partagée entre toutes les versions...

Le changelog est affiché en page d'accueil de https://faros.lephare.com/

2024-07-03 12:38 UTC, thislg requested changes
Mettre à jour la liste des changements en page d'accueil.

2024-07-05 07:10 UTC, thislg approved these changes

2024-07-05 07:10 UTC, thislg commented on docs/static/index.md
> +### 2024-07-04
```suggestion
### 2024-07-05
```

2024-07-05 07:17 UTC, merged