fix: update references to latest version (2024.07)
le-phare/le-phare.github.io pull request #178
Opened 2024-07-17 07:35 UTC by pierreboissinot

2024-07-17 07:38 UTC, thislg approved these changes

2024-07-17 07:39 UTC, thislg requested changes

2024-07-17 07:39 UTC, thislg commented on docs/generated/versions_pages/2024.07.md
>  nav_order: 1
Il faut changer la nav_order dans tous les autres fichiers.

2024-07-17 08:05 UTC, pierreboissinot commented on docs/generated/versions_pages/2024.07.md
>  nav_order: 1
bien vu, merci

2024-07-19 07:47 UTC, thislg approved these changes

2024-07-19 07:48 UTC, merged